Fix build. Capture exceptions instead of throwing errors to the console.
ybw0014/ExoticGarden-CN pull request #29
Opened 2024-05-25 08:14 UTC by QwQ-dev

Fix build.

Stop using deprecated BlockStorage. Catch exceptions from BlockDataController#createBlock(Location, String) in Schematic#pasteSchematic(Location, Tree, boolean) to prevent console spam.

2024-05-25 17:39 UTC, ybw0014 requested changes

2024-05-25 17:39 UTC, ybw0014 commented on src/main/java/io/github/thebusybiscuit/exoticgarden/schematics/Schematic.java
> +                            if (org.bukkit.Tag.LEAVES.isTagged(material) && ThreadLocalRandom.current().nextInt(100) < 25) {
导入 Tag

2024-05-25 17:39 UTC, ybw0014 commented on src/main/java/io/github/thebusybiscuit/exoticgarden/schematics/Schematic.java
> +                                        Optional.ofNullable(SlimefunItem.getByItem(tree.getItem()));
我记得 SlimefunItem 好像有 getOptionalByItem

2024-05-26 00:06 UTC, QwQ-dev commented on src/main/java/io/github/thebusybiscuit/exoticgarden/schematics/Schematic.java
> +                                        Optional.ofNullable(SlimefunItem.getByItem(tree.getItem()));
看了下，在原版 Slimefun 中具有，但汉化版没有该方法

https://github.com/Slimefun/Slimefun4/blob/master/src/main/java/io/github/thebusybiscuit/slimefun4/api/items/SlimefunItem.java#L1169

https://github.com/SlimefunGuguProject/Slimefun4/blob/master/src/main/java/io/github/thebusybiscuit/slimefun4/api/items/SlimefunItem.java#L1243

2024-05-26 03:54 UTC, StarWishsama commented
请使用 dev 作为基底分支。

2024-05-26 11:58 UTC, QwQ-dev commented on src/main/java/io/github/thebusybiscuit/exoticgarden/schematics/Schematic.java
> +                            if (org.bukkit.Tag.LEAVES.isTagged(material) && ThreadLocalRandom.current().nextInt(100) < 25) {
其已经导入了 io.github.thebusybiscuit.exoticgarden.schematics.org.jnbt.Tag

2024-05-26 12:39 UTC, ybw0014 requested changes

2024-05-26 12:39 UTC, ybw0014 commented on src/main/java/io/github/thebusybiscuit/exoticgarden/schematics/Schematic.java
> +import io.github.thebusybiscuit.exoticgarden.schematics.org.jnbt.*;
不要使用星号`*`导入

2024-05-27 00:43 UTC, QwQ-dev commented on src/main/java/io/github/thebusybiscuit/exoticgarden/schematics/Schematic.java
> +import io.github.thebusybiscuit.exoticgarden.schematics.org.jnbt.*;
已完成: https://github.com/SlimefunGuguProject/ExoticGarden/pull/29/commits/6fbbbc39ea33bb61332d0325dae12756fc0552f3

2024-06-17 13:45 UTC, ybw0014 approved these changes

2024-06-17 13:45 UTC, merged